Add ko2iblnd.conf to lustre rpm
Otherwise it breaks the rpm build:

  .....
  error: Installed (but unpackaged) file(s) found:
     /etc/modprobe.d/ko2iblnd.conf

  RPM build errors:
     Installed (but unpackaged) file(s) found:
     /etc/modprobe.d/ko2iblnd.conf