LUS-11587 o2ib: MOFED 5.5+ ib_dma_virt_map_sg
MOFED 5.5 fails with:
  ERROR: "ib_dma_virt_map_sg" [.../ko2iblnd.ko] undefined!

See if we have a broken ib_dma_map_sg() and provide
a suitable replacement for the missing functionality.

Lustre-change: https://review.whamcloud.com/50711
Lustre-commit: cc5594df3e70d1924f34ccdf4c3178654d277ad0

Signed-off-by: Shaun Tancheff <shaun.tancheff@hpe.com>
Change-Id: Ic7d7d2f59b40aa23be9d3da751038ec355c6502f
Reviewed-on: https://es-gerrit.hpc.amslabs.hpecorp.net/162372
Reviewed-by: Petros Koutoupis <pkoutoupis@cray.com>
Reviewed-by: Alexey Lyashkov <alexey.lyashkov@hpe.com>
Tested-by: Elena Gryaznova <elena.gryaznova@hpe.com>