LUS-12933 build: Compatibility updates for kernel v6.15
Linux commit v3.11-8733-g55f841ce9395
  super: fix calculation of shrinkable objects for small number
Added vfs_pressure_ratio()
Linux commit v6.14-rc1-13-g52e66823e0be
  fs: dcache: move the sysctl to fs/dcache.c
Removed sysctl_vfs_cache_pressure. Use vfs_pressure_ratio()
and provide a vfs_pressure_ratio() for older kernels.
Also keep a minimum of 99 ldlm objects.

Linux commit v6.14-rc1-45-ge33ce6bd4ea2
  mm: Remove grab_cache_page_write_begin()
Open code grab_cache_page_write_begin() from folio-compat until
direct folio support is landed.

Linux commit v6.14-rc1-61-gd96e2802a802
  mm: Remove wait_on_page_locked()
Open code wait_on_page_locked() from folio-compat until
direct folio support is landed.

Linux v6.12-rc1-119-g908a1d775422
  hrtimers: Introduce hrtimer_setup() to replace hrtimer_init()
Provide a compat hrtimer_setup() for older kernels

Linux commit v6.14-rc4-9-g88d5baf69082
  Change inode_operations.mkdir to return struct dentry *
Provide a ll_vfs_mkdir and mkdir wrappers for older kernels

zfs 2.3.3 build fails with:

lustre/include/obd_support.h:977:49: error: pointer/integer type \
mismatch in conditional expression [-Werror]
  977 |                 kmem_cache_zalloc(slab, (type)) :
      |                                                 ^

Workaround with an explicit inline wrapper for kmem_cache_zalloc()

Lustre-change: https://review.whamcloud.com/59970
Lustre-commit: 323a6672b7c06834ffdc8cbc7051f645233d34e1

WC-bug-id: LU-19137
Signed-off-by: Shaun Tancheff <shaun.tancheff@hpe.com>
Change-Id: I2b6f1ed41cfc2f8e8324b654d26fb91957bf3042
Reviewed-on: https://es-gerrit.hpc.amslabs.hpecorp.net/163479
Reviewed-by: Alexander Boyko <alexander.boyko@hpe.com>
Reviewed-by: Nikitas Angelinas <nikitas.angelinas@hpe.com>
Tested-by: Vitaly Fertman <vitaly.fertman@hpe.com>