LUS-13095 build: unused 'ni'
lnet/klnds/gnilnd/gnilnd.c:37:18: error: \
   unused variable 'ni' [-Werror=unused-variable]

Fixes: aa2fa25325 ("LU-10391 lnet: support setting LND timeouts")
Signed-off-by: Shaun Tancheff <shaun.tancheff@hpe.com>
Change-Id: Ic16ce7a6af1bf95578137f0ce43bd3d3639f1b83
Reviewed-on: https://es-gerrit.hpc.amslabs.hpecorp.net/163467
Tested-by: Jenkins Build User <nssreleng@cray.com>
Reviewed-by: Cory Spitz <cory.spitz@hpe.com>
Reviewed-by: Nikitas Angelinas <nikitas.angelinas@hpe.com>
Reviewed-by: Christopher Horn <chris.horn@hpe.com>