LUS-12935 build: page_cache_alloc removed, missing return
Fix gcc -Wimplicit-function-declaration
   file.c:678:24: error: implicit declaration of function \
   page_cache_alloc [-Werror=implicit-function-declaration]

Fixes: 4a14a51a8e0 ("LU-18448 llite: read dir on open")
Signed-off-by: Shaun Tancheff <shaun.tancheff@hpe.com>
Change-Id: If063b9cbbfc112ce09dd4a904407b9f7c81d77b1
Reviewed-on: https://es-gerrit.hpc.amslabs.hpecorp.net/163362
Reviewed-by: Andrew Perepechko <andrew.perepechko@hpe.com>
Reviewed-by: Alexey Lyashkov <alexey.lyashkov@hpe.com>
Reviewed-by: Petros Koutoupis <petros.koutoupis@hpe.com>
Tested-by: Vitaly Fertman <vitaly.fertman@hpe.com>