LUS-12693 tests: save_lustre_params() fix
save_lustre_params() and restore_lustre_params()
are to fail if Lustre parameters are missing to
avoid the false-positive behavior of tests.

  # ONLY=216 sh sanity.sh
  == sanity test 216: check lockless
  error: get_param: param_path 'osc/*/contention_seconds':
    No such file or directory
  error: set_param: param_path 'osc/*/contention_seconds':
    No such file or directory
  error: set_param: setting 'osc/*/contention_seconds'='60':
    No such file or directory
  directio on /mnt/lustre/f216.sanity for 10x4096 bytes
  PASS

Fixes: e628a59ade ("b=11270 Lockless i/o and lockless truncate code and sanityN tests")
Fixes: 7921d0d8db ("LU-9980 tests: save specific facet in save_lustre_params()")
Signed-off-by: Elena Gryaznova <elena.gryaznova@hpe.com>
Change-Id: Idb23bfb8b18ec68f0b0a3d9c84b93a0a539dc330
Reviewed-on: https://es-gerrit.hpc.amslabs.hpecorp.net/163168
Reviewed-by: Alexey Lyashkov <alexey.lyashkov@hpe.com>
Reviewed-by: Alexander Zarochentsev <alexander.zarochentsev@hpe.com>