LUS-8201 kfilnd: Integrate with LNet health
The following LNet health message statuses are integrated into kfilnd.

LNET_MSG_STATUS_LOCAL_ERROR: Local error, such as failure to allocate
memory, occurred.

LNET_MSG_STATUS_REMOTE_ERROR: Failure to perform an asynchronous send,
tagged send, read, or write operation. Since there is no connection
status to rely on, the assumption made is that the target failed to
allocate fabric targetable resources which caused the asynchronous
operation to fail.

LNET_MSG_STATUS_LOCAL_NO_ROUTE: Failure to get peer's KFI address. The
assumption made is that the underlying kfabric provider failed to
resolve the node and service strings into a provider specific address.

LNET_MSG_STATUS_LOCAL_TIMEOUT: Failure to perform initial immediate,
bulk request, RMA, or bulk response operation within the allotted LND
timeout window.

LNET_MSG_STATUS_REMOTE_TIMEOUT: Failure of the target to perform the
bulk response operation within the initiator's allotted LND timeout
window.

LNET_MSG_STATUS_NETWORK_TIMEOUT: KFI completion queue error event
occurred with the error ETIMEDOUT.

The following LNet health message statuses are not integrated into
kfilnd.

LNET_MSG_STATUS_LOCAL_INTERRUPT: Unused in LNet and other LNDs.

LNET_MSG_STATUS_LOCAL_DROPPED: Message dropped due to failure to
establish a connection. Since KFILND is connectionless, this does not
apply.

LNET_MSG_STATUS_REMOTE_DROPPED: Remote peer has dropped the message
due to the connection going down. Since KFILND is connectionless, this
does not apply.

LNET_MSG_STATUS_LOCAL_ABORTED: Connection has been aborted. Since
KFILND is connectionless, this does not apply.

Signed-off-by: Ian Ziemba <iziemba@cray.com>
Change-Id: I83389c6d461765075df189bb2d0927600964c52e
Reviewed-on: https://es-gerrit.dev.cray.com/156343
Reviewed-by: Frank Zago <fzago@cray.com>