LUS-10713 build: Require %{name}-osd-ldiskfs-mount package
Builds using alternate lustre name (Ex: lustre_ib) break on install
due to conflict over what provides and requires the
  lustre-osd-ldiskfs-mount
package. The error appears as:

   error: Failed dependencies:
     lustre-osd-ldiskfs-mount = 2.14.57_174_g61ffe28 is needed by
     kmod-lustre_ib-osd-ldiskfs-2.14.57_174_g61ffe28-1.el8.x86_64

This can be seen by the provides/requires of the affected packages:

   $ rpm -qp lustre_ib-osd-ldiskfs-mount-2.14.57_174_g61ffe28-1.el8.x86_64.rpm \
      --provides  | grep -v -E 'ksym|kernel|rpmlib'
   lustre-osd-mount = 2.14.57_174_g61ffe28
   lustre_ib-osd-ldiskfs-mount = 2.14.57_174_g61ffe28-1.el8
   lustre_ib-osd-ldiskfs-mount(x86-64) = 2.14.57_174_g61ffe28-1.el8

and:

   $ rpm -qp kmod-lustre_ib-osd-ldiskfs-2.14.57_174_g61ffe28-1.el8.x86_64.rpm \
     --requires | grep -v -E 'ksym|kernel|rpmlib' | sort | uniq
   /bin/sh
   kmod-lustre_ib = 2.14.57_174_g61ffe28
   ldiskfsprogs >= 1.44.3.wc1
   lustre-osd-ldiskfs-mount = 2.14.57_174_g61ffe28
   /usr/sbin/depmod
   /usr/sbin/weak-modules

Signed-off-by: Shaun Tancheff <shaun.tancheff@hpe.com>
Change-Id: Ie428c28d93ab28adc22d3a31d369183b8585269f
Reviewed-on: https://es-gerrit.dev.cray.com/159993
Tested-by: Jenkins Build User <nssreleng@cray.com>
Reviewed-by: Chris Horn <chris.horn@hpe.com>
Reviewed-by: Petros Koutoupis <pkoutoupis@cray.com>