LUS-10804 tests: get maxage param on mds1 properly
The correct maxage parameters on mds1:
  osp.${FSNAME}-MDT000[1-N]-osp-MDT0000.maxage

To reproduce the failure just run the following on
failover setup where mds1_HOST != mds1failover_HOST:
  sh llmount.sh
  ONLY="100b 100c" sh replay-single.sh

  error: get_param: param_path
   'osp/*MDT0000*MDT0001/maxage': No such file or directory
  sleep: missing operand
  Try 'sleep --help' for more information.

Fixes: 436cd4fd21 ("LU-14938 tests: fail_abort() in t-f to take care of MDTs")
Test-Parameters: testlist="replay-single recovery-small"
Signed-off-by: Elena Gryaznova <elena.gryaznova@hpe.com>
Change-Id: I4c478b5aaabf3666561ce682c6ffe79070e49bbe
Reviewed-on: https://es-gerrit.dev.cray.com/160497
Reviewed-by: Alexander Boyko <c17825@cray.com>
Reviewed-by: Vladimir Saveliev <vlaidimir.saveliev@hpe.com>
Tested-by: Elena Gryaznova <elena.gryaznova@hpe.com>