LU-10973 lutf: Fix order of linking for python modules
LUTF normally works but in some test cases at startup we got:

ImportError: lustre/test/lutrf/src/_lnetconfig.so:
undefined symbol: lustre_lnet_del_ni

If you check the symbol is there. The issue is the linking order.
We need to put the generated module name before all its
dependencies.

Also, remove cfs_expr_list_match from string.h, move the definition
to nidstrings.c, and make it static.

Test-Parameters: @lnet
Change-Id: Ia57fbd9d5795d845ea14bc1416f968383afcba2b
Signed-off-by: James Simmons <jsimmons@infradead.org>
Signed-off-by: Timothy Day <timday@amazon.com>
Reviewed-on: https://review.whamcloud.com/c/fs/lustre-release/+/46478
Tested-by: jenkins <devops@whamcloud.com>
Tested-by: Maloo <maloo@whamcloud.com>
Reviewed-by: Serguei Smirnov <ssmirnov@whamcloud.com>
Reviewed-by: Frank Sehr <fsehr@whamcloud.com>
Reviewed-by: Cyril Bordage <cbordage@whamcloud.com>
Reviewed-by: Oleg Drokin <green@whamcloud.com>