LU-6142 utils: Fix compile warning in lfs_project
In strncpy(), providing size less than destination
will leave last byte untouch. This is what the
compiler is complaining about. Since, strncpy()
gurantees NUL termination for anyting after length
of source. The correct usage is to provide the
full length of destination.

$ uname -r
6.12.0-124.20.1.el10_1.x86_64

$ gcc --version
gcc (GCC) 14.3.1 20250617

lfs_project.c: In function ‘project_clear_one’:
lfs_project.c:258:17: error: ‘strncpy’ output may be truncated copying 255 bytes from a string of length 255 [-Werror=stringop-truncation]
  258 |                 strncpy(lp.project_name, bname, NAME_MAX);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lfs_project.c: In function ‘project_set_one’:
lfs_project.c:219:17: error: ‘strncpy’ output may be truncated copying 255 bytes from a string of length 255 [-Werror=stringop-truncation]
  219 |                 strncpy(lp.project_name, bname, NAME_MAX);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Test-Parameters: trivial
Signed-off-by: Arshad Hussain <arshad.hussain@aeoncomputing.com>
Change-Id: Ic09e5a70e9651ea6855d297c83932755a44e848e
Reviewed-on: https://review.whamcloud.com/c/fs/lustre-release/+/64381
Tested-by: jenkins <devops@whamcloud.com>
Reviewed-by: Chakshu Kansal <ckansal@ddn.com>
Tested-by: Maloo <maloo@whamcloud.com>
Reviewed-by: Andreas Dilger <adilger@thelustrecollective.com>
Reviewed-by: Oleg Drokin <green@whamcloud.com>