LUS-12645 build: fix the common.postinst nonexistence issue
Since dkms v3.1.3, the common.postinst script was not installed
anymore with the install-redhat target, which caused the following
failure while installing lustre-client-dkms package:

  WARNING: /usr/lib/dkms/common.postinst does not exist.
  ERROR: DKMS version is too old and lustre-client was not
  built with legacy DKMS support.
  You must either rebuild lustre-client with legacy postinst
  support or upgrade DKMS to a more current version.

This patch fixes the above issue by using dkms add, build,
and install commands directly instead of the common.postinst script.

Lustre-change: https://review.whamcloud.com/57392
Lustre-commit: a2b5118f2a6fa17aaeb3ec0554b6ea8a3ad62ddd
Lustre-author: Jian Yu <yujian@whamcloud.com>

WC-bug-id: LU-18533
Signed-off-by: Shaun Tancheff <shaun.tancheff@hpe.com>
Change-Id: I74eaf68e264a347d55982cad1e6e2ad3fa7672a3
Reviewed-on: https://es-gerrit.hpc.amslabs.hpecorp.net/163164
Tested-by: Jenkins Build User <nssreleng@cray.com>
Reviewed-by: Rajeev Mishra <rajeevm@hpe.com>
Reviewed-by: Caleb Carlson <caleb.carlson@hpe.com>
Reviewed-by: Petros Koutoupis <petros.koutoupis@hpe.com>