LUS-12934 build: s_shrink may be a pointer
Fix gcc -Wimplicit-function-declaration
   llite_lib.c:1532:21: error: 'sb->s_shrink' is a pointer;

With the introduction of
  Linux commit v6.6-rc4-53-gc42d50aefd17
    mm: shrinker: add infrastructure for dynamically allocating...

Most kernels have change s_shrink to a pointer however RHEL 9.6
in particular has not, breaking the presumption that if
alloc_shrinker() is present s_shrink would be a pointer.

Fixes: d9c5501caf6 ("LUS-12626 llite: reclaim dentries/inodes in smaller amounts")
Signed-off-by: Shaun Tancheff <shaun.tancheff@hpe.com>
Change-Id: I12815ed77e08230c0b9b9e859a7146d71cac6a1d
Reviewed-on: https://es-gerrit.hpc.amslabs.hpecorp.net/163363
Reviewed-by: Alexander Zarochentsev <alexander.zarochentsev@hpe.com>
Reviewed-by: Andrew Perepechko <andrew.perepechko@hpe.com>
Tested-by: Vitaly Fertman <vitaly.fertman@hpe.com>