LUS-13237 llite: update shrinker for el7
This effectively reverts LUS-12626 on kernels that are too old to
support it.

.../lustre/llite/rw.c:908:9: error: missing braces around \
initializer [-Werror=missing-braces]
  struct ll_readahead_state ras = { 0 };

Fixes: 984a20b8c2db ("LUS-12626 llite: reclaim dentries/inodes in smaller amounts")
Fixes: 9618a7fe3185 ("LUS-11367 readahead: simplification")
Signed-off-by: Shaun Tancheff <shaun.tancheff@hpe.com>
Change-Id: I4e9ffb42375ca9ee37d654d02182ef824be471d3
Reviewed-on: https://es-gerrit.hpc.amslabs.hpecorp.net/163572
Reviewed-by: Alexander Zarochentsev <alexander.zarochentsev@hpe.com>
Reviewed-by: Andrew Perepechko <andrew.perepechko@hpe.com>
Tested-by: Vitaly Fertman <vitaly.fertman@hpe.com>