LUS-11800 build: Use brackets "[]" around sh conditionals
Correctly place logical conditional tests within [] brackets
to resolve a syntax error that fails with:

  Checking for file conflicts: .........................[done]
  /var/tmp/rpm-tmp.bTJFgI: line 6: -f: command not found
  /var/tmp/rpm-tmp.bTJFgI: line 7: -f: command not found
  WARNING: /usr/libexec/dkms/common.postinst does not exist.
  ERROR: DKMS version is too old and cray-lustre-client was not
  built with legacy DKMS support.

Fixes: 0678731bcc ("LUS-11641 cray-obs: subproject cray-lustre-client-dkms")
Signed-off-by: Shaun Tancheff <shaun.tancheff@hpe.com>
Change-Id: I0db7763777373c43271dda5e16eaa53ae75e205f
Reviewed-on: https://es-gerrit.hpc.amslabs.hpecorp.net/162501
Reviewed-by: Petros Koutoupis <pkoutoupis@cray.com>
Reviewed-by: Chris Horn <chris.horn@hpe.com>
Tested-by: Elena Gryaznova <elena.gryaznova@hpe.com>