LUS-7811 osd: quota support for 4.4.140 and new
Special inodes numbers "EXT4_USR_QUOTA_INO" and "EXT4_GRP_QUOTA_INO"
were removed from ext4_valid_inum() since kernel version 4.4.140.
It leads to the next error
LustreError: 0-0: lustre-MDT0000: can't enable quota enforcement since
space accounting isn't functional...

This patch is part of LU-11412 to fix quota.

WC-bug-id: LU-11412
Signed-off-by: Jian Yu <yujian@whamcloud.com>
Signed-off-by: Alexander Boyko <c17825@cray.com>
Change-Id: I67eee705c2610153bccbd08bb8b8e08b3b4bfe76
Reviewed-on: https://es-gerrit.dev.cray.com/155765
Reviewed-by: Shaun Tancheff <stancheff@cray.com>
Reviewed-by: Alexander Zarochentsev <c17826@cray.com>
Tested-by: Alexander Lezhoev <c17454@cray.com>